# Generated by Django 2.0.5 on 2018-05-09 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='Pdf_articulo',
            field=models.FileField(upload_to=''),
        ),
    ]
