# Generated by Django 2.0.3 on 2018-04-03 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
        ('foros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cuentas.Usuarios'),
        ),
    ]
