# Generated by Django 2.0.3 on 2018-04-09 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foros', '0003_carrera_inscripcion_materia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='Nombre_Carrera',
            field=models.CharField(choices=[('ISC', 'IngSistemasComputacionales'), ('LCM', 'Medicina')], default='ISC', max_length=5),
        ),
    ]
