# Generated by Django 2.0.3 on 2018-04-09 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foros', '0004_auto_20180409_0825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregunta',
            name='user',
        ),
        migrations.AddField(
            model_name='pregunta',
            name='Carrera',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='foros.Carrera'),
        ),
    ]
