# Generated by Django 2.0.3 on 2018-04-10 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foros', '0005_auto_20180409_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='Nombre_Carrera',
            field=models.CharField(max_length=5),
        ),
    ]
