# Generated by Django 2.0.3 on 2018-04-11 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0003_auto_20180404_2344'),
        ('foros', '0006_auto_20180410_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregunta',
            name='Carrera',
        ),
        migrations.AddField(
            model_name='pregunta',
            name='Materia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='foros.Materia'),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cuentas.Usuarios'),
        ),
        migrations.AlterField(
            model_name='carrera',
            name='Nombre_Carrera',
            field=models.CharField(max_length=30),
        ),
    ]
