# Generated by Django 2.0.3 on 2018-04-19 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foros', '0008_auto_20180418_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario_articulo',
            name='Fecha_Publicacion',
            field=models.DateTimeField(auto_now=True, verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='respuesta_pregunta',
            name='Comentarios',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='foros.Respuesta_Pregunta'),
        ),
        migrations.AddField(
            model_name='respuesta_pregunta',
            name='Fecha_Publicacion',
            field=models.DateTimeField(auto_now=True, verbose_name='date published'),
        ),
    ]
