# Generated by Django 2.0.3 on 2018-04-19 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foros', '0009_auto_20180419_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario_articulo',
            name='Comentarios',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='foros.Comentario_Articulo'),
        ),
    ]
