# Generated by Django 2.0.3 on 2018-04-19 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foros', '0010_comentario_articulo_comentarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Respuesta_PreguntaHijos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Texto_Respuesta', models.CharField(max_length=200)),
                ('Fecha_Publicacion', models.DateTimeField(auto_now=True, verbose_name='date published')),
            ],
        ),
        migrations.RemoveField(
            model_name='respuesta_pregunta',
            name='Comentarios',
        ),
        migrations.AddField(
            model_name='respuesta_preguntahijos',
            name='Comentarios',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='foros.Respuesta_Pregunta'),
        ),
        migrations.AddField(
            model_name='respuesta_preguntahijos',
            name='Pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foros.Pregunta'),
        ),
    ]
