# Generated by Django 2.0.3 on 2018-04-19 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foros', '0011_auto_20180419_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuesta_preguntahijos',
            name='Comentarios',
        ),
        migrations.RemoveField(
            model_name='respuesta_preguntahijos',
            name='Pregunta',
        ),
        migrations.AddField(
            model_name='respuesta_pregunta',
            name='Comentarios',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='foros.Respuesta_Pregunta'),
        ),
        migrations.DeleteModel(
            name='Respuesta_PreguntaHijos',
        ),
    ]
